# =========================
# Application
# =========================
spring.application.name=api-gateway
server.port=8091

# =========================
# Eureka
# =========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =========================
# Gateway Discovery
# =========================
spring.cloud.gateway.server.webmvc.routes[0].id=catalog-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/catalog-service/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

# =========================
# Logging
# =========================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.discovery=TRACE
logging.level.org.springframework.cloud.gateway.route=TRACE
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG

# =========================
# Actuator (for debugging)
# =========================
management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted